services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678" # Porta padrão do n8n
    environment:
      # Sua URL de acesso (Importante para Webhooks)
      - N8N_HOST=sua_url_ou_ip.com
      - N8N_PROTOCOL=http # Ou https, se estiver usando proxy reverso
      - N8N_PORT=5678
      # Senha e E-mail de login
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=seu_usuario
      - N8N_BASIC_AUTH_PASSWORD=sua_senha_forte
      # Configuração de persistência de dados internos (importante)
      - DB_TYPE=sqlite
    volumes:
      # Mapeia o volume para salvar os dados do n8n fora do container
      - ~/.n8n:/home/node/.n8n
    container_name: n8n-container
